### ISSUE TITLE
Click to open the file and nothing loads

### ISSUE THREAD

**Issue by henrypearce4D** [xy-gao/splatviz-blender#2]
![image](https://github.com/user-attachments/assets/08f999ae-427a-46a2-8a1b-8d8cded6c48c)

Very cool addon!

After I click Open the file browser and double click my .ply nothing loads. I have a message in the console, is it related?

**Comment by xy-gao** [comment]
@henrypearce4D the warning is ok. need to switch your viewport shading to material preview or render preview.

**Comment by henrypearce4D** [comment]
thanks I see now you did that in the video, perhaps could you write that in the instructions?
